class data():
    baseURL = "https://demowebshop.tricentis.com/"
    firstName = "Aldian"
    firstNameBlank = ""
    lastName = "Karim"
    lastNameBlank = ""
    email = "gepengkrn13039@gmail.com"
    emailBlank = ""
    emailInvalid = "gepengkrn12"
    password = "123456"
    passwordBlank = ""
    passwrod_less_6 = "123"
    ConfirmPassword = "123456"
    ConfirmPasswordBlank = ""
    ConfirmPasswordInvalid = "kerenbgt"
    message = "Tolong dikirim secepat mungkin!!!"
    msg_email_failed = "The specified email already exists"
    msg_firstName_blank = "First name is required."
    msg_lastName_blank = "Last name is required."
    msg_email_blank = "Email is required."
    msg_email_invalid = "Wrong email"
    msg_password_blank = "Password is required."
    msg_password_not_match = "The password and confirmation password do not match."
    msg_password_less_6_char = "The password should have at least 6 characters."
    msg_login_email_blank = "Login was unsuccessful. Please correct the errors and try again."
    msg_login_email_blank_1 = "No customer account found"
    msg_login_password_blank = "The credentials provided are incorrect"
    msg_payment_information_COD = "You will pay by COD"
    msg_thanks_you = "Thank you"
    msg_success_order = "Your order has been successfully processed!"
    msg_invalid_format_email = "Please enter a valid email address."
    msg_invalid_recipient_name = "Enter valid recipient name"
    msg_invalid_recipient_email = "Enter valid recipient email"
    msg_invalid_sender_name = "Enter valid sender name"
    msg_invalid_email_name = "Enter valid sender email"
    msg_invalid_qty = "Quantity should be positive"


class title():
    title_welcome = "Welcome to our store"
    title_welcome1 = "Welcome to the new Tricentis store!"
    title_welcome2 = "Feel free to shop around and explore everything."
    title_register = "Register"
    title_featured = "FEATURED PRODUCTS"
    product_name = "$25 Virtual Gift Card"
    allert_success = "The product has been added to your shopping cart"
    title_pay_method = "2\nPayment Method"
    title_confirm_order = "4\nConfirm Order"
